# Generated by Django 5.2.5 on 2025-08-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainmentt', '0002_remove_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Timeout', 'Timeout')], default='Pending', max_length=20),
        ),
    ]
