# Generated by Django 5.2.5 on 2025-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainmentt', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paied_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Timeout', 'Timeout'), ('Free', 'Free')], default='Pending', max_length=20),
        ),
    ]
