# Generated by Django 5.2.5 on 2025-09-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainmentt', '0005_requestlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
