# Generated by Django 5.2.5 on 2026-02-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entertainmentt", "0006_delete_requestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
    ]
