# Generated by Django 5.2.5 on 2026-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entertainmentt", "0007_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_using",
            field=models.BooleanField(default=True),
        ),
    ]
