# Generated by Django 5.2.5 on 2026-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entertainmentt", "0008_order_is_using"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_using",
        ),
        migrations.AddField(
            model_name="car",
            name="is_using",
            field=models.BooleanField(default=True),
        ),
    ]
