# Generated by Django 5.2.5 on 2026-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entertainmentt", "0009_remove_order_is_using_car_is_using"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("global_price", models.IntegerField(default=10000)),
                ("global_price_minutes", models.IntegerField(default=60)),
            ],
        ),
    ]
