# Generated by Django 5.2.5 on 2026-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entertainmentt", "0010_systemsetting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsetting",
            name="global_price_minutes",
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="global_price",
            field=models.IntegerField(default=1000),
        ),
    ]
